version: "3.9"

services:
  lipsync:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
    stdin_open: true
    tty: true
    command: >
      python src/cli.py
      --face /app/input.mp4
      --audio /app/input.wav
      --outfile /app/output.mp4
